/**
 * CloudFormation Template Validation Tests
 *
 * This test suite validates the CloudFormation templates generated by our constructs
 * to ensure they follow AWS best practices, security principles, and proper resource
 * naming conventions.
 */
export {};
//# sourceMappingURL=template-validation.test.d.ts.map